spring:
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
  application:
    name: SpringJWTJdk17
  datasource:
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    username: poly
    url: jdbc:mariadb://localhost:3306/myDB
jwt:
  token:
    creator: poly
    access:
      valid:
        time: 300
      name: jwtAccessToken
    refresh:
      valid:
        time: 3000
      name: jwtRefreshToken
  secret:
    key: '12345678123456781234567812345678123456781234'
server:
  port: '15000'
